function [MASQ_Output, MASQ_GDA, MASQ_AA, MASQ_GDD, MASQ_AD, MASQ_total] = apathy(window)

%JAC 
%MASQ short 62 item. Permissions from David Waston, Jan 2013 
%%% Initialize the screen
% [window, screenRect] = Screen(0,'OpenWindow');
HideCursor;
white = [255 255 255];

% Clear the screen
SCREEN(window,'FillRect',0); % clear screen
% Set font size
SCREEN(window,'TextSize',32);
Screen(window,'TextFont', 'Verdana');	%	Use Verdana because both Macs and PCs have this.


% Initial instructions
SCREEN(window,'TextSize',32);
SCREEN(window,'DrawText','Instructions:',300,100,white);
SCREEN(window,'TextSize',24);
SCREEN(window,'DrawText','The following items will be a list of feelings, sensations, problems, and experiences that  ',25,250,white);
SCREEN(window,'DrawText','people sometimes have. Read each item and then choose the option that best describes how',25,300,white);
SCREEN(window,'DrawText','much you have felt or experienced things this way during the past week, including today.',25,350,white);
SCREEN(window,'DrawText','Press the spacebar to begin',300,450,white);
GetResp('space');

% The questions or symptoms
questions = { ...
    'Felt sad.', ...
    'Startled easily.', ...
    'Felt cheerful', ...
    'Felt afraid', ...
    'Felt discouraged', ...
    'Hands were shaky', ...
    'Felt optimistic', ...
    'Had diarrhea', ...
    'Felt worthless', ...
    'Felt really happy', ...
    'Felt nervous', ...
    'Felt depressed', ...
    'Was short of breath', ...
    'Felt uneasy', ...
    'Was proud of myself', ...
    'Had a lump in my throat', ...
    'Felt pain', ...
    'Felt unattractive', ...
    'Had hot or cold spells', ...
    'Had an upset stomach', ...
    'Felt like a failure', ...
    'Felt like I was having a lot of fun', ...
    'Blamed myself for a lot of things', ...
    'Hands were cold or sweaty', ...
    'Felt withdrawn from other people', ...
    'Felt keyed up, on edge', ...
    'Felt like I had a lot of energy', ...
    'Was trembling or shaking', ...
    'Felt inferior to others', ...
    'Had trouble swallowing', ...
    'Felt like crying', ...
    'Was unable to relax', ...
    'Felt really slowed down', ...
    'Was disappointed in myself', ...
    'Felt nauseous', ...
    'Felt hopeless', ...
    'Felt dizzy or lightheaded', ...
    'Felt sluggish or tired', ...
    'Felt really “up” or lively', ...
    'Had pain in my chest', ...
    'Felt really bored', ...
    'Felt like I was choking', ...
    'Looked forward to things with enjoyment', ...
    'Muscles twitched or trembled', ...
    'Felt pessimistic about the future', ...
    'Had a very dry mouth', ...
    'Felt like I had a lot of interesting things to do', ...
    'Was afraid I was going to die', ...
    'Felt like I had accomplished a lot', ...
    'Felt like it took extra effort to get started', ...
    'Felt like nothing was very enjoyable', ...
    'Heart was racing or pounding', ...
    'Felt like I had a lot to look forward to', ...
    'Felt numbness or tingling in my body', ...
    'Felt tense or “high-strung”', ...
    'Felt hopeful about the future', ...
    'Felt like there wasn’t anything interesting or fun to do', ...
    'Seemed to move quickly and easily', ...
    'Muscles were tense or sore', ...
    'Felt really good about myself', ...
    'Thought about death or suicide', ...
    'Had to urinate frequently'};

% Run the questionnaire (one loop for each question)
for qnum = 1:62
    
    currQuest = questions{qnum};
    Qname = ['Question ' num2str(qnum)];
    
    % Display question, get response
    SCREEN(window,'FillRect',0); % clear screen
    SCREEN(window,'TextSize',24);
    SCREEN(window,'DrawText',Qname,25,100,white);
    SCREEN(window,'TextSize',32);
    SCREEN(window,'DrawText',currQuest,100,250,white);
    
    SCREEN(window,'TextSize',24);
    SCREEN(window,'DrawText','1',75,400,white);
    SCREEN(window,'DrawText','NOT AT ALL',10,450,white);
    
    SCREEN(window,'TextSize',24);
    SCREEN(window,'DrawText','2',260,400,white);
    SCREEN(window,'DrawText','A LITTLE BIT',220,450,white);
    SCREEN(window,'TextSize',20);
%     SCREEN(window,'DrawText','It did not',210,550,white);
%     SCREEN(window,'DrawText','bother me',210,580,white);
%     SCREEN(window,'DrawText','much',210,610,white);

    SCREEN(window,'TextSize',24);
    SCREEN(window,'DrawText','3',500,400,white);
    SCREEN(window,'DrawText','MODERATELY',425,450,white);
    SCREEN(window,'TextSize',20);
%     SCREEN(window,'DrawText','It was very',400,550,white);
%     SCREEN(window,'DrawText','unpleasant',400,580,white);
%     SCREEN(window,'DrawText','but I could',400,610,white);
%     SCREEN(window,'DrawText','stand it',400,640,white);
    
    SCREEN(window,'TextSize',24);
    SCREEN(window,'DrawText','4',680,400,white);
    SCREEN(window,'DrawText','QUITE A BIT',630,450,white);
    SCREEN(window,'TextSize',20);
%     SCREEN(window,'DrawText','I could',620,550,white);
%     SCREEN(window,'DrawText','barely',620,580,white);
%     SCREEN(window,'DrawText','stand it',620,610,white);
    SCREEN(window,'TextSize',24);
    SCREEN(window,'DrawText','5',855,400,white);
    SCREEN(window,'DrawText','EXTREMELY',825,450,white);
    SCREEN(window,'TextSize',20);

    resp(qnum) = GetResp('1!','2@','3#','4$','5%')+1;
    
end
%general distress anxious, anxious arousal, general depressive, and
%anhedonic depression
MASQ_Output=resp; 
MASQ_GDA = resp(4)+resp(8)+resp(11)+resp(14)+resp(16)+resp(20)+resp(26)+resp(32)+resp(35)+resp(55)+resp(59)
MASQ_AA = resp(2)+resp(6)+resp(13)+resp(17)+resp(19)+resp(24)+resp(28)+resp(30)+resp(37)+resp(40)+resp(42)+resp(44)+resp(46)+resp(48)+resp(52)+resp(54)+resp(62)
MASQ_GDD = resp(1)+resp(5)+resp(9)+resp(12)+resp(21)+resp(23)+resp(29)+resp(31)+resp(34)+resp(36)+resp(38)+resp(45)
MASQ_AD = resp(18)+resp(25)+resp(33)+resp(41)+resp(50)+resp(51)+resp(57)+resp(61)+6-resp(3)+6-resp(7)+6-resp(10)+6-resp(15)+6-resp(22)+6-resp(27)+6-resp(39)+6-resp(43)+6-resp(47)+6-resp(49)+6-resp(53)+6-resp(56)+6-resp(58)+6-resp(60)
MASQ_total = MASQ_GDA+MASQ_AA+MASQ_GDD+MASQ_AD
% Tally up scores, get Prom and Prev score
% anxiety_responses = resp;
% anxiety_score = sum(resp);

% screen('closeall');




